### ISSUE TITLE
Widgets WIP

### ISSUE THREAD

**Issue by Nessus85100** [Ignoble61/script.skinshortcuts#1]
I've tested the "widgets" and have some feedback. The new properties added by the new way of selecting widgets are not helping to distinguish all the widgets especially those from the library nodes. For example if you select different widget from the same library and type eg... Movies - Action and Movies - Adventures, then the two properties, that can be used to StringCompare the visible/hidden the lists, are the same...
```
<property name="widget">Library</property>
<property name="widgetName">Movies - Action</property>
<property name="widgetType">movies</property>
```
```
<property name="widget">Library</property>
<property name="widgetName">Movies - Adventures</property>
<property name="widgetType">movies</property>
```
Of course they show and hide fine but the animations (based on the properties "widget" or "widgetType") are not working at all since they are the same.

If you select widgets from the same library but different type then the animations starting to act weird 
 and the "hidden" animation is broken. I have no idea if this is because an $INFO is used in the content tag of if is some bug in the script. You can reproduce it if you just put and simple fade animation as visible/hidden condition to any widget that the `<content>` tag starts with $INFO.

**Comment by Ignoble61** [comment]
Thanks for the feedback :)

If you're using a traditional skinshortcuts implementation (rather than ... dare I even whisper it ;) ... templates) then my expectation is that you'd be using the same list to show all library movies content, so it wouldn't be possible to animate between two widgets in the same list. It's the same as with submenus, where you can't animated between different submenu's because they're all displayed in a single list. I may be misunderstanding, though.

If animations aren't working when using an $INFO tag then I would think that would be a Kodi issue not a skinshortcuts one (even when using templates, its gui xml at runtime thats failing), but I'll see if I can reproduce when I have some time.

**Comment by Ignoble61** [comment]
Just to say I was able to recreate the issue pretty easily, but I'm still going to say it's a Kodi issue, not a Skin Shortcuts one.

**Comment by Nessus85100** [comment]
>If you're using a traditional skinshortcuts implementation (rather than ... dare I even whisper it ;) ... templates) then my expectation is that you'd be using the same list to show all library movies content, so it wouldn't be possible to animate between two widgets in the same list. It's the same as with submenus, where you can't animated between different submenu's because they're all displayed in a single list. I may be misunderstanding, though.

Yes, i am on the traditional way and using the same list id for every type of content (Movies, TVShows etc) with a stringcompare to the widget property as a visible condition and so far everything working fine with my (in overrides.xml) widgets...
```
<control type="fixedlist" id="35">
  <include>HomeWidgets_MoviesListVars</include>
  <visible>StringCompare(Container(20).ListItem.Property(Widget),SmartishMovies)</visible>
  <content>plugin://service.smartish.widgets?type=movies&amp;reload=$INFO[Window(Home).Property(smartish.movies)]</content>
</control>
```
```
<control type="fixedlist" id="45">
  <include>HomeWidgets_TVShowsListVars</include>
  <visible>StringCompare(Container(20).ListItem.Property(Widget),SmartishTVShows)</visible>
  <content>plugin://service.smartish.widgets?type=episodes&amp;reload=$INFO[Window(Home).Property(smartish.episodes)]</content>
</control>
```
Is there a better way to do this, without the templates ?. 


>Just to say I was able to recreate the issue pretty easily, but I'm still going to say it's a Kodi issue, not a Skin Shortcuts one.

@phil65 can you please have a look at this. Is the same issue that we discussed here... https://github.com/BigNoid/script.skinshortcuts/issues/23#issuecomment-120306182

Cheers
Nessus

**Comment by Ignoble61** [comment]
Better is very relative. From a quick glance, that code looks like it would work fine. Some may find using the new 'path' property better, and including those in the same list instance as other widgets with a 'movies' or 'tvshows' type. Others may find doing something clever with $PARAMS better. At the end of the day, skin shortcuts just provides information about which widget has been chosen, its entirely up to the skin what it does with that information.

If, though, there are any extra parameters that skin shortcuts could return, this is the time to request them as I'm coming close to finishing the new widgets code.

**Comment by Nessus85100** [comment]
I don't mind to use the path property way (assuming that the $INFO issue in content tag will fixed) but to make any kind of animation to work between widgets, we need a property the it will be different for every widget. With this new way of selecting widgets, currently there is no such property. The widgetID, (that we use for the skinner's defined widgets in overrides.xml), with the new way is the same for many widgets.

**Comment by Ignoble61** [comment]
Not sure how that would possibly work - the big work of this update is to add library nodes, sources, playlists and add-ons to what the user can easily select to use as a widget. Unless it's possible to predict every single library node the user may select, every single source and so on, they're going to have to share a list at some point because it's simply not going to be possible to create individual lists for each one. The properties (notably widget and widgetType) are hopefully enough that they can be pulled into a small number of lists designed to display that media type.

Ultimately the animation issue is exactly as it is for submenu's - they share a list, so it's not possible to animate between them. The issue with giving them their own lists is the same as well - it's impossible to know how many there will be to set up a predefined list. It's one of the buggers of giving users ultimate choice ;) and I'm not aware of any non-template solutions.

(Though obviously, for your own widgets, you can keep as you're doing and give them a unique widgetID so that you can handle them individually - indeed, the only way you'd want to do a weather widget, for example.)

I'll look into the skin strings, but I make no promises - it will depend on how much code it takes / how many behaviours I have to work around. TBH, I'm not going to put a lot of time into working around issues that are already solved via templates. (Though I fully respect if you choose not to use them :) )

**Comment by Nessus85100** [comment]
The issue with this new way is the many different types of content (regarding the aspect ratio thumbs and the available info labels) that the user can set as widgets but not enough "tools" to show the those widgets in a proper and attractive way. Kodi uses [Container.Content(parameter)] (http://kodi.wiki/view/List_of_Boolean_Conditions) boolean condition for that. Is this something that can be done here ?.

In any case, the bigger issue is the same list animation issue. Giving the choice to the users for unlimited widgets without the ability to display them properly, it's no goal at least for me.

**Comment by Ignoble61** [comment]
Add-ons don't have it (yet - because I can't work out how to get it via JSON calls yet). For others, the equivalent of the Container.Content(parameter) condition is the widgetType. It should definitely be set correctly for playlists. As the docs say, if it's being reported wrongly for library nodes, please report it :) (there are lots of edge cases with library nodes, where the node itself - index.xml - doesn't report a content type, but the views within it do. Right now, the script is taking a 'best guess' in these cases, and may not always get it right - yet!)

**Comment by Ignoble61** [comment]
OK, I've looked into using skin strings. Short version: It can't be added in a good way, so I won't add it.

Long version: There are numerous elements to setting skin strings reliably. The two most notable - we have to be able to set them for all profiles, even if they're not logged in; we have to be able to clear them reliably (again, for all profiles) when they're no longer valid.

As regards the first - we can misuse the skins .hash file to do this. It'll work, but that isn't what that file is designed for.

For the second - potentially the skins .hash file could be misused again, but it actually becomes a hellishly more complicated process to do this, as the state of various skin strings would need to be maintained between different builds (which doesn't happen at all at the moment - the .hash file is generated entirely anew on a skin build, with its purpose being to determine if a new skin build is needed). It could be done, but would need refactoring and a lot of testing. And the nature of the way that properties are linked to menu items means its surprisingly difficult to get links to skin strings that are no longer needed.

The big issues, though, are twofold - as already said, the issue is already solved via new methods provided by the script; this is a Kodi issue that is being worked around - the best solution would be to solve it in Kodi, not in the script (as loath as I am to recommend the horror that is the forums, that may be the best place to highlight the issue and get it fixed in core).

Sorry :(

**Comment by Nessus85100** [comment]
So, if i understand correctly there is no way to use this new choosing widgets method properly unless you move to templates... right?.  If this is the only option then I could "dive" inside but please make the documentation little more understandable because i had a look of it and i still i have no idea how this stuff is working.

**Comment by Ignoble61** [comment]
I think it's a little harsh to say there's no way to use the new method without templates :) The job of Skin Shortcuts here is to let the user select a widget (including the new options) and give the skin enough information to display that widget. A limitation of the traditional implementations means that animating between widgets is difficult, but if there are properties missing to actually display them then please do say what they are / what their values should be - if they are missing then yes, there would be no way to use the new method.

If you want to animate between all the different possible widgets then I'm right behind templates. That was the purpose of adding them (actually, the idea was to be able to animate between submenus, but it extends to widgets). That's not to say there aren't potentially other possibilities - I still haven't got my head around $PARAM's, but I've been told more than once that the templates possibly duplicate what they do :)

Documentation wise, of course I'll take another pass at it (tomorrow). Let me know if there is anything specific that is unclear. A couple of simple examples, if they help -

```
	<template>
		<other include="widget">
			<condition tag="property" attribute="name|widget">SmartishMovies</condition>
			<controls>
				<control type="fixedlist" id="35">
				 	<include>HomeWidgets_MoviesListVars</include>
				 	<skinshortcuts>visibility</skinshortcuts>
				 	<content>plugin://service.smartish.widgets?type=movies&amp;reload=$INFO[Window(Home).Property(smartish.movies)]</content>
				</control>
			</controls>
		</other>
		<other include="widget">
			<condition tag="property" attribute="name|widgetType">movies</condition>
			<property name="content" tag="property" attribute="widgetPath" />
			<controls>
				<control type="fixedlist" id="35">
				 	<include>HomeWidgets_MoviesListVars</include>
				 	<skinshortcuts>visibility</skinshortcuts>
				 	<content>$SKINSHORTCUTS[content]</content>
				</control>
			</controls>
		</other>
	</template>
```

The first is the templates version of the movies widget you posted earlier in the thread. It checks if for `<property name="widget">SmartishMovies</property>`. (Not a particularly interesting or useful example, as that can be done entirely skin-side as is)

The second is more interesting - it checks for `<property name="widgetType">movies</property>`, then assigns `$SKINSHORTCUTS[content]` to the value of `<property name="widgetPath" />` - it then creates individual lists for each item which matches the condition with the `<content />` tag set to the widgetPath property.

Because both examples set the `includes="widget"`property, they both get included in the skin with `<include>skinshortcuts-template-widget</include>`

**Comment by Nessus85100** [comment]
Ok... i have a couple of questions
1. This must be done for both custom predefined skin's widgets and those set by the new way (nodes) ?
2. Where do i put that include in the skin since the fixed list's that i use are now included in the templates.xml ?
3. In the docs you say.... "If this file is present, skin shortcuts will automatically build your templates alongside its traditional includes". Where this is stored ?. I don't see anything in script-skinshortcuts-includes.xml.
4. Since they are no real action examples of this, can i send you my shortcuts files and skin includes of my skin and modified them to work with templates ?. Of course not all but some examples for the different kind of widgets that i use in my skin. Or you can send me your skin code integration  and templates/shortcuts code to see it in real action.

**Comment by Ignoble61** [comment]
1. That's up to you. As I said in the example, the first one can be done entirely skin side - so do it entirely skin side if you like :) (the thing to watch is that no template matches it!). My personal plan - though it's not coded up yet - is to have my weather/pvr/system widgets (those that won't appear in lists ;)) in an include in the skin, then have a matching template's `<controls />` simply be an `<include>relevantwidgetinclude</include>` for those.
2. Wherever you want in the skins .xml. I include it in my home.xml, before my main/submenu includes (because I want the widgets to appear behind them). I actually include it within a group with those widgets I don't build via templates - the code is
```
		<control type="group">
			<left>0</left>
			<top>520</top>
			<width>600</width>
			<height>200</height>
			<include>Gaze-Home-Widgets</include>
			<include>skinshortcuts-template-widget</include>
		</control>
```
3. The template.xml goes in the skins 'shortcuts' folder, alongside any overrides.xml (I'll make this clearer in the docs). The script-skinshortcuts-overrides.xml still needs to be included somewhere as with traditional implementation - the templates includes are written into that.
4. Sure, but bear with me if it takes me a day or two to look at it. It's unlikely to be useful to you for me to send you my own implementation as my skin is massively broken at the moment and has a couple of dependancies that exist nowhere but my development machine (I've been playing with using a script to generate blurred fanart, and then using masks to display it - the home page looks great, but the rest of the skin is in a hell of a state!)

**Comment by Nessus85100** [comment]
> The template.xml goes in the skins 'shortcuts' folder, alongside any overrides.xml (I'll make this clearer in the docs). The script-skinshortcuts-overrides.xml

I have no such file. I have the `script-skinshortcuts-includes.xml` and there is nothing inside regarding templates.

>1. That's up to you. As I said in the example, the first one can be done entirely skin side - so do it entirely skin side if you like :) (the thing to watch is that no template matches it!). My personal plan - though it's not coded up yet - is to have my weather/pvr/system widgets (those that won't appear in lists ;)) in an include in the skin, then have a matching template's <controls /> simply be an <include>relevantwidgetinclude</include> for those.
 2. Wherever you want in the skins .xml. I include it in my home.xml, before my main/submenu includes (because I want the widgets to appear behind them). I actually include it within a group with those widgets I don't build via templates - the code is

I will give a look again to see if can manage to do this in the meantime i will send you my files and of course don't worry about the time. Whenever you can is fine. Can you send me your mail at nessus85100@hotmail.com ?

**Comment by Ignoble61** [comment]
You need to create a template.xml file, alongside and in the same folder as any overrides.xml file your skin provides. The template.xml file is where you define your templates, which then get written to script-skinshortcuts-includes.xml. Without that file, there won't be any mention of templates in the other.

You can e-mail it to my gmail account - eeeeepish@gmail.com, but please leave a note here when you have done. It's primarily a junk account, so I'll need to go in to specifically retrieve your message.

**Comment by Nessus85100** [comment]
> You need to create a template.xml file, alongside and in the same folder as any overrides.xml file your skin provides. The template.xml file is where you define your templates, which then get written to script-skinshortcuts-includes.xml. Without that file, there won't be any mention of templates in the other.

That's what i did exactly but still see don't any templates related includes in script-skinshortcuts-includes.xml file. You can see for your self.

Files sent.

**Comment by Ignoble61** [comment]
Turns out there was a bug in the templates implementation which means 'other' templates only got built if there was a main menu template. Fixed in this branch, and I've e-mailed you back a sample template.xml file + updated overrides.xml file using paths for skin widgets.

**Comment by Nessus85100** [comment]
Thanks a lot mate. Will check/test them and report back with any results.

Cheers
Nessus

**Comment by Nessus85100** [comment]
Hi @Ignoble61. I've try to test the files but i get an "unable to build menu" script error.
Here is the debug log... http://xbmclogs.com/pq6yxywch

**Comment by Ignoble61** [comment]
The error is caused by a typo in the script. Now fixed in this branch, and cheers. The fact the error is being triggered at all means the overrides.xml I sent you isn't valid (I copied and pasted from my own overrides.xml - I must have got it wrong.) I'll try and spot the error this evening and send you a corrected version.

**Comment by Nessus85100** [comment]
No need for that. I just spot it. It was a stringcompare visible condition inside a path attribute. 
Main menu is building fine now. We report back with further tests.

Thanks
Nessus

**Comment by Nessus85100** [comment]
@Ignoble61 i tested and i am impress how this works, although i have some issues/questions.

1.First of all, my custom widgets that i use `<includes>` with static content....
`<widget label="5" type="mixed" path="<include>SettingsContent</include>">Settings</widget>`
`<widget label="31379" type="mixed" path="<include>CustomItems</include>">CustomItems</widget>`
are making all my custom widgets not show in the widget select dialog. Only nodes are available. If i remove those all the others are showing fine. Must be some problem with `<include>` tag inside the `path` attribute. 

2.Besides thumbs (that are defined with fixed lists in the templates.xml) i have several info labels that they are different for every widget and they show only when the list has focus. With the old way i used stringcompares to the widgetID to show those info. Now which is the best way to do the same ?

3.The "Recently added movies" and "Recently added episodes" nodes they set the widgetType property as "video" and not as "movies"-"tvshows/episodes" (causing wrong thumb to show up). Is that normal or some kind of bug because the "In progress TV shows" they have a "tvshows" widgetType property.

4.If i want to add another widgetType to an `<other include="widget">`can i do it by adding another condition or do i have to add a whole new `<other include="widget">` ?
I mean something like this:
`<condition tag="property" attribute="name|widgetType">tvshows</condition>`
`<condition tag="property" attribute="name|widgetType">episodes</condition>`

That's all for now. Again... excellent work !!!

Thanks
Nessus

**Comment by Ignoble61** [comment]
1. Sounds like a bug, I'll look into it in the next couple of days

2. Include them in the same template? (You can probably do something clever with <skinshortcuts>visibility</skinshortcuts> to get them to appear correctly, and there should be no problem passing that to a $PARAM, for example, though I've never tried it, depending how you have them set up)

3. Probably a bug but it depends on what xml files are available for them in the video library nodes. I'll see what I can do, again in the next couple of days.

4. At the moment there's no OR conditions, they're all AND. Maybe in a future variant of templates. So, for now, you'd have to include another template.

**Comment by Ignoble61** [comment]
Number 3 should now be fixed :)

**Comment by Ignoble61** [comment]
4 can now also be done - below your condition tags:-
`<match>any</match>`
Will mean the template will match if any of the conditions match, rather than the default of behaviour of all conditions having to match.

**Comment by Nessus85100** [comment]
Unable to building menu... http://xbmclogs.com/pcwv6kkc1
Let me know if you need a full debug log.

**Comment by Ignoble61** [comment]
Damn, now I'm going to have to fix that problem properly ;)

Thanks for the bug report, commit which introduced error now reverted.

**Comment by Nessus85100** [comment]
Sorry, still getting an error... http://pastebin.com/HQK9fmj2

**Comment by Ignoble61** [comment]
That'll teach me to only look at the first error in a log! Didn't need to revert that commit, but I will need to look into the problem properly (this evening) - the log seems to be saying that an object isn't the type of object it should be...

**Comment by Nessus85100** [comment]
:wink:

**Comment by Nessus85100** [comment]
> Edit: From a test, all you need do is escape them, the library will do the rest - so
`path="&lt;include&gt;CustomItems&lt;/include&gt;"`

By the way this is not working properly. It's not giving an error but the path property it looks like this : 
`<property name="widgetPath">&lt;include&gt;SettingsContent&lt;/include&gt;</property>`

**Comment by Ignoble61** [comment]
What platform are you running on?

**Comment by Nessus85100** [comment]
Windows

**Comment by Ignoble61** [comment]
See my updated comment right above your last one (I was obviously typing it at the same time as you!)

**Comment by Ignoble61** [comment]
OK, I've had a play with it and the comment I said to ignore is actually broadly correct. The script sets and loads the 'text' property of a given xml node (in this case the `<property name="widgetPath">` node. As we're setting/loading text - and not adding subnodes - the elementtree library is kindly ensuring that the string that we save is escaped, as xml isn't valid as the text property of an element.

It would be technically possible to work around this in code (would need to find a way to check whether a given string is xml, and if so to load it as an xml node and add it as a subnode to the property node, and do something similar on the return journey, but that's going to be incredibly complicated to do, and would lead to even more confusion when the script tries to use it further on (as we're going to have to deal with two different possible object types for the nodes 'text' value).

A possible alternative from the skin shortcuts side, may be to support something like $INCLUDE[includename] as the path in templates, but it'll take a better coder than I to support including further XML nodes within the traditional includes file.

**Comment by Ignoble61** [comment]
This will only work with templates - the traditional include method will show `<property name="widgetPath">$INCLUDE[CustomItems]</property>`, but you can now set the widgetPath to `$INCLUDE[CustomItems]`, assign that to a template property, use that in an element within the template (e.g. `<content>$SKINSHORTCUTS[myProperty]</content>`) and it will be replaced with `<include>CustomItems</include>`. Best workaround I can come up with.

**Comment by Nessus85100** [comment]
Fisrst of all about these...
>Number 3 should now be fixed

> 4 can now also be done - below your condition tags:-
`<match>any</match>`

Both are working fine. This `<match>any</match>` tag reduces the code in templates.xml a lot. Great job !!!.

Some other things that i have questions....

-- With the last commit i get a "Library" entry (linking to video library) in all my submnenus even for those main menu items that i haven't set any submenu. Is that a bug ?

-- I use the `widgetName` property to check when the widget is genres so i can use a different list layout (i cant think a better way to do this... do you ?). With the last commit some extra spaces are added between and the end of the widgetName....

before the last commit:
`<property name="widgetName">Movies - Genres</property>`
after the last commit:
`<property name="widgetName">Movies  - Genres </property>`
note the extra space after the word "Movies" and after the word "Genres".

From my testings this is also happening for any entry that is not in the root of the video or music library. If select any item from the root of the libraries (eg Recently added episodes) the widgetName property value is showing properly.

-- I can't understand how this `widgetTarget` property works. I see it when select a library node item (eg In progress TV shows) but shouldn't this be added by the script in the skinshortcuts-template-widget include to the appropriate `<content>` tags ?... or i must define it also and for the libraries nodes items in template.xml ? (which IMHO is wrong). By the way the target tag is required only when the action/onclick needs to open in the appropriate window, not when the items are playable items. ATM it's added to every library node item but as long as it's working it's fine by me.

>A possible alternative from the skin shortcuts side, may be to support something like $INCLUDE[includename] as the path in templates, but it'll take a better coder than I to support including further XML nodes within the traditional includes file.

So, atm there is no way to use custom skin widgets with static content `<includes>` ?

**Comment by Ignoble61** [comment]
> With the last commit i get a "Library" entry (linking to video library) in all my submnenus even for those main menu items that i haven't set any submenu. Is that a bug ?

I can't reproduce this. Can you please test with the skin shortcut default menus (temporarily rename your skins shortcuts folder, then reset the menu) to see if it still happens. I presume you're not using a template for the submenu, so it's showing in the traditional implementations include...?

> I use the widgetName property to check when the widget is genres so i can use a different list layout (i cant think a better way to do this... do you ?). With the last commit some extra spaces are added between and the end of the widgetName....

Nice spot. Fixed, thanks.

> I can't understand how this widgetTarget property works. I see it when select a library node item (eg In progress TV shows) but shouldn't this be added by the script in the skinshortcuts-template-widget include to the appropriate <content> tags ?

At the moment, its up to the skinner to assign it to a property, then use that property in the `<content target="" /> attribute. It might be possible to have it auto-assigned, but I can imagine that would cause more issues down the line ;)

You don't have to include it in your own widgets if you don't want to. Y'know, I need to test whether this is possible (which won't be for an hour or two at least, as I've just installed the latest Mac OS beta and it's causing havoc with my mouse cursor which I'm going to have to sort out first, but if the following isn't yet possible, it will be before the night is out (and was certainly my intention to include, whether I ever got round to it)...

```
<property name="target" tag="property" attribute="name|widgetTarget" />
<property name="target"></property>
```

Which would set the property to the value of widgetTarget, if the main menu has a widgetTarget property, or set it to "" if it doesn't.

I know that the target is only needed for displaying folders, but when library nodes can have media and folders in them, as can add-ons, as can sources, I personally find it more useful to just set it, knowing Kodi will ignore it when it's not needed (and it saved me quite a lot of code in my own template.xml file!)

**Comment by Nessus85100** [comment]
>With the last commit i get a "Library" entry (linking to video library) in all my submnenus even for those main menu items that i haven't set any submenu. Is that a bug ?

>I can't reproduce this. 

I find out what causing this. It's the visible condition in this shortcut in the videos.DATA.xml submenu. If i keep only one of the three visible conditions in there then the problem is fixed. If i put more than one then the problem occurs again. It was working fine until now. I haven't touch that file for months.
```
<shortcut>
	<label>14022</label>
	<label2 />
	<defaultID>14022</defaultID>
	<icon />
	<thumb />
	<action>ActivateWindow(Videos,root)</action>
  <visible>Library.HasContent(Movies) | Library.HasContent(TVShows) | Library.HasContent(MusicVideos)</visible>
</shortcut>
```

**Comment by Nessus85100** [comment]
> It might be possible to have it auto-assigned, but I can imagine that would cause more issues down the line ;)

How this can cause issues if it will assigned only for the library nodes widgets ?. For all those nodes widgets, if the target is not assigned they wont work.

**Comment by Ignoble61** [comment]
And I haven't touched the visibility code at all within the widget branch (that I know of). If you can find a particular commit where it broke that might give some clues, otherwise I'll have a play around when I have time (probably tomorrow). Seems very odd that that leads to it appearing in all menus :confused: 

Big potential issue comes from simply how it works. It would need thinking about whether every time there's a `<content />` tag (and a widgetType property), the template automatically adds a target="" attrib, or whether it would do it if the skinner had a blank one in there, or maybe if the skinner /didn't/ have a blank one in there (so they can specify it directly if they want), or if the skinner has one with a particular value in it which tells the script to fill it (which we pretty much have already, with the addition of two `<property />` elems - or just one if they're happy for it to be blank if there isn't a widgetType property). And does the script do it for every content tag it finds, or just for the first one if there are multiple lists (I have one widget which displays two lists from the template, only one of which I want the target attrib filled for). And do we do it for just one widget, or do we handle multiple templates here (widgetType./x/). And so on ;)

So many possible scenarios that skinners may want to do with widget implementations, if its done it needs to be done in a way that hopefully no skinner is asking for it to be done a different way down the line - or leave it up to the skinner how and where the target attrib gets filled :)

**Comment by Nessus85100** [comment]
> And I haven't touched the visibility code at all within the widget branch (that I know of). If you can find a particular commit where it broke that might give some clues, otherwise I'll have a play around when I have time (probably tomorrow). Seems very odd that that leads to it appearing in all menus :confused:

Will do that and let you know when this started.

> Big potential issue comes from simply how it works. It would need thinking about whether every time there's a <content /> tag (and a widgetType property), the template automatically adds a target="" attrib, or whether it would do it if the skinner had a blank one in there, or maybe if the skinner /didn't/ have a blank one in there (so they can specify it directly if they want), or if the skinner has one with a particular value in it which tells the script to fill it (which we pretty much have already, with the addition of two <property /> elems - or just one if they're happy for it to be blank if there isn't a widgetType property). And does the script do it for every content tag it finds, or just for the first one if there are multiple lists (I have one widget which displays two lists from the template, only one of which I want the target attrib filled for). And do we do it for just one widget, or do we handle multiple templates here (widgetType./x/). And so on ;)

:frowning:  Yea, you are right... leave it up to the skinner is the best choice right now.
>This will only work with templates - the traditional include method will show <property name="widgetPath">$INCLUDE[CustomItems]</property>, but you can now set the widgetPath to $INCLUDE[CustomItems], assign that to a template property, use that in an element within the template (e.g. <content>$SKINSHORTCUTS[myProperty]</content>) and it will be replaced with <include>CustomItems</include>. Best workaround I can come up with.

Can you please elaborate a little more on this. What should i change in path tag in overrides.xml and in templates.xml as you already know i want to use the templates future for the widgets selection and as soon as i fully understand how it works maybe will do the same and for the main menu and submenus.

**Comment by Ignoble61** [comment]
In overrides.xml:-

`<widget label="Test" path="$INCLUDE[CustomItem]">Test</widget>`

In the relevant template:-

The property can be assigned with something like

`<property name="path" tag="property" attribute="name|widgetPath" />`

and then in the controls

`<content>$SKINSHORTCUTS[path]</content>`

Will lead to:-

```
<content>
	<include>CustomItem</include>
</content>
```

**Comment by Nessus85100** [comment]
Works like a charm. Thanks. By the way one thing i notice during testing this if you use the just select method (which i use for the "Custom Items" widget) the label that is return by the `skinLabel` is with the `>` in the end of the label if the item is a folder. Example: "Apple iTunes Trailers" it returns "Apple iTunes Trailers >".

> And I haven't touched the visibility code at all within the widget branch (that I know of). If you can find a particular commit where it broke that might give some clues, otherwise I'll have a play around when I have time (probably tomorrow). Seems very odd that that leads to it appearing in all menus :confused:

>Will do that and let you know when this started.

I only could narrow the issue between this one: d9c9442db76af18fae680920649c6dd8dc7ea8ed and this one: eae500f6f849303ee9d56db1782c87f863911f16 since all the others are giving me an unable to build menu error.

**Comment by Nessus85100** [comment]
Continuing on testing this i have some more questions/requests...

-- When you select a video source as widget is it possible to determine if that source contains Movies, TVShows, Episodes or plain videos so we can assign the proper layout list and info labels. I mean something like Kodi does in which file and library mode are the same. In music playlist is not a big problem because the thumbs are always squared although also in that case the info labels are missing.

-- How can i group my skin widgets in overrides.xml so to be shown as groups in select widget dialog ?. I've try some examples with `<groupings>` from script's default overrides.xml but i couldn't make it work.

-- And one bug (I think!). When you try to select a library node, they are available nodes that they are not exist yet in the library. I notice that in music library where the "singles" node was available to select as widget but since i dont have any singles in my library it's not showing in the music library items. This causes the widget to be assigned to the main menu item but no list is created in skinshortcuts-template-widget include.

I forgot to say this, but the script... is flying regarding the speed and it's not only 50% faster. It's 10 times faster !!!. Also this freakin "templates" stuff makes all the lists to show instantly regardless the number of items in them. I tested with a widget with 1000+ items and it shows and navigates through the other widgets... instantly !!!.

Awesome work !!!

**Comment by Ignoble61** [comment]
Visibility should (hopefully!) now be fixed - actually a problem introduced in the build changes intro'd to the main branch recently (I think...), so I'll backport it when I know it's fixed.

I'll try to look at other issues tonight, but it's been a long day so it may not happen. Off the top of my head:-

Will fix the label for the Just Select, and thanks for the bug report.

The sources may not be possible (I'll check the json introspect later, but I don't think Kodi gives us that info.)

I was hoping no-one was going to ask for that ;) You can put them into a single group, but you can't include, for example, some in with the video add-ons, some in with the sources, some in with music library nodes if you want to be able to set them as default. It would need some refactoring of the code that works out where in the grouping the user is.

Yup, at present skin shortcuts doesn't take account of the visibility conditions of library nodes. I'm sure there was a reason I coded it like that, but I honestly can't remember what it was... I'll see what can be done.

Glad you're liking the speed improvements. The 'official' guesstimate is that the two changes to the way menus are built should give anything between a 90 and 95% improvement in build speed. Glad to see that's being borne out :)

**Comment by Nessus85100** [comment]
> I was hoping no-one was going to ask for that ;) 

:grin:
> You can put them into a single group, but you can't include, for example, some in with the video add-ons, some in with the sources, some in with music library nodes if you want to be able to set them as default. It would need some refactoring of the code that works out where in the grouping the user is.

No, i don't use any defaults. I like the first look of my skin as clean as possible. Can i group them to my own separate groups like "Movies Widgets", "TV Shows Widgets" etc. If yes can you give me sample code for that ?

**Comment by Ignoble61** [comment]
You should be able to achieve what you want by defining your widgets within `<widget-groupings />` within your skins overrides.xml file by defining each widget via a `<shortcut />` node within a custom `<node />` node.

```
<widget-groupings>
	<node label="Movie Widgets (or localised string)">
		<shortcut label="[widgetName]" type="[type used in select dialog label2]" icon="[icon to display in select dialog]" widget="[widget]" widgetType="[widgetType]" widgetTarget="[widgetTarget]">[widgetPath]</shortcut>
		<shortcut />
		<shortcut />
		...
	</node>
	<node label="TV Shows Widgets">
		...
	</node>
</widget-groupings>
```

And actually, if you did want to define defaults, you could still do so with a`<widgetdefaultnode />` in the overrides.xml (but that's a lot messier than defining defaults the classic way!). You can also remove the `<content>widgets</content>` node if all your widgets are defined this way.

A couple of things to note about this method (1) Whilst this method is used within the widget-groupings for add-ons, it's not been tested with only some of the widget properties - it may just work, or errors may need to be reported and time given to fix! (2) It's possible the scripts `widget-groupings` may change before the code is all done, so it's worth checking for any changes there when the new widget code is ready for primetime.

**Comment by Nessus85100** [comment]
>A couple of things to note about this method (1) Whilst this method is used within the widget-groupings for add-ons, it's not been tested with only some of the widget properties - it may just work, or errors may need to be reported and time given to fix! (2) It's possible the scripts widget-groupings may change before the code is all done, so it's worth checking for any changes there when the new widget code is ready for primetime.

Then i will leave it as it is for now until the new widgets code is finished or maybe i could leave it like this permanently if it is possible when a widget is defined and you open the select dialog to select a new one, it focused in that defined widget ?

> Visibility should (hopefully!) now be fixed - actually a problem introduced in the build changes intro'd to the main branch recently (I think...), so I'll backport it when I know it's fixed.

It's fixed. Thanks.

>The sources may not be possible (I'll check the json introspect later, but I don't think Kodi gives us that info.)

Ok, no problem. Thanks.

> Yup, at present skin shortcuts doesn't take account of the visibility conditions of library nodes. I'm sure there was a reason I coded it like that, but I honestly can't remember what it was... I'll see what can be done.

IMHO we need to change this otherwise we would have many users reports who will refer this as bug, which obviously is not.

**Comment by Ignoble61** [comment]
OK...

* Just Select labels (and actually a few other cases where the folder indicator wasn't being removed) are now fixed

* Getting the content type for sources isn't possible. Kodi just doesn't give this information via Json (that I can see)

* I've put in quick support for only showing library nodes if their visibility conditions match. I haven't tested this extensively (particularly in the Explorer function - which loads nodes differently from how the root of the nodes are loaded), so if you come across any bugs let me know. Just a side note, it's been like this ever since library nodes were added, and I'm not aware of any user reporting it as a bug ;)

(And if I remember why I didn't do this in the first place - and it's a good reason - I reserve the right to revert this change!)

* I was right, all the widget properties were needed when using `<shortcut />` to define widgets. They're now not (just the widget="" attrib, so the script knows to process it as a widget), and will be loaded if present, otherwise the appropriate property will be set to a blank string.

* Thanks for confirmation that it's fixed. I finally managed to recreate it myself, so I've done a PR to BigNoid's master to fix it, and I'll rebase the widgets branch on that when it gets merged. And nice spot in the first place :)

* Nope, it's not possible to highlight any particular option. The select dialog doesn't have any method to highlight a particular item, either natively or via the hack I'm using to access it. (Unless you mean putting back the * indicator that a particular widget is the default item which is on my todo list, but needs a new way to do as the select widget code has been moved out of the gui code)

**Comment by Nessus85100** [comment]
> Just Select labels (and actually a few other cases where the folder indicator wasn't being removed) are now fixed

It's fixed. Thanks

> I was right, all the widget properties were needed when using <shortcut /> to define widgets. They're now not (just the widget="" attrib, so the script knows to process it as a widget), and will be loaded if present, otherwise the appropriate property will be set to a blank string.

I did some tests on this but if i am not doing something wrong, this method needs to add also and the libraries nodes as a `<shortcut />` in overrides.xml ?. If yes, then i will leave the widgets ungrouped.

> I've put in quick support for only showing library nodes if their visibility conditions match. I haven't tested this extensively (particularly in the Explorer function - which loads nodes differently from how the root of the nodes are loaded), so if you come across any bugs let me know.

I don't have any other use cases to test it but the "Singles" node in music library is not showing in the select (and just select) widget dialog or the choose shortcut dialog. Of course it's your choice to revert this. After all is your work. I just thought that it will cause support headaches to the skinners but whatever you think is right is fine with me.

Thanks again for all your hard work.

**Comment by Ignoble61** [comment]
The snippet was an example of what you could add to a `<widget-groupings />` in your own overrides.xml. The rest of it should be as copied-pasted from the scripts overrides.xml. (So the library nodes and whatnot are still defined by `<content />` elems.)

**Comment by Ignoble61** [comment]
Thanks for all your help testing this :)
